spring:
  main:
    banner-mode: "off"
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - RewritePath=/profile/(?<path>.*), /$\{path}
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
          filters:
            - RewritePath=/billing/(?<path>.*), /$\{path}
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application/**
          filters:
            - RewritePath=/application/(?<path>.*), /$\{path}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

management:
  security:
    enabled: false