spring:  
  application:
    name: profile-service
  cloud:
    consul:
      host: ${CONSUL_SERVER:127.0.0.1}
      port: ${CONSUL_PORT:8500}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:33062}/profiles
    username: profiles
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

#---
#spring:
#  profiles: zone1
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone1

#---
#spring:
#  profiles: zone2
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone2